/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function extract(html: string): NapiResult<ExtractResultNapi>

export declare function extractBytes(html: Buffer): NapiResult<ExtractResultNapi>

export declare function extractBytesWithOptions(html: Buffer, options?: OptionsNapi | undefined | null): NapiResult<ExtractResultNapi>

export interface ExtractResultNapi {
  contentText?: string
  contentHtml?: string
  contentMarkdown?: string
  commentsText?: string
  commentsHtml?: string
  images: Array<ImageDataNapi>
  metadata: MetadataNapi
  classificationConfidence?: number
  extractionQuality: number
  warnings: Array<string>
}

export declare function extractWithOptions(html: string, options?: OptionsNapi | undefined | null): NapiResult<ExtractResultNapi>

export interface ImageDataNapi {
  src: string
  filename: string
  alt?: string
  caption?: string
  isHero: boolean
}

export interface MetadataNapi {
  title?: string
  author?: string
  url?: string
  hostname?: string
  description?: string
  siteName?: string
  date?: string
  categories: Array<string>
  tags: Array<string>
  id?: string
  fingerprint?: string
  license?: string
  language?: string
  image?: string
  pageType?: string
}

export interface OptionsNapi {
  includeComments?: boolean
  includeTables?: boolean
  includeImages?: boolean
  includeLinks?: boolean
  favorPrecision?: boolean
  favorRecall?: boolean
  targetLanguage?: string
  url?: string
  authorBlacklist?: Array<string>
  deduplicate?: boolean
  minExtractedSize?: number
  minExtractedLen?: number
  maxExtractedLen?: number
  minOutputSize?: number
  minOutputCommSize?: number
  minScore?: number
  maxDuplicateRatio?: number
  maxLinkDensity?: number
  minParagraphCluster?: number
  includeFormatting?: boolean
  onlyWithMetadata?: boolean
  maxTreeDepth?: number
  minWordLength?: number
  useFallbackExtraction?: boolean
  dedupCacheSize?: number
  includeTitleInContent?: boolean
  outputMarkdown?: boolean
  pageType?: string
}
